version: '3.9'

services:
    backend-qtim:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-qtim
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres-qtim
            - redis-qtim
        ports:
            - '3000:3000'
        environment:
            DATABASE_URL: postgresql://admin:admin@postgres-qtim:5432/qtim
            REDIS_URL: redis://redis-qtim:6379
        entrypoint: >
            sh -c "
              npm run migrate:deploy &&
              npm run seed &&
              npm run prod
            "

    postgres-qtim:
        image: postgres:15
        container_name: postgres-qtim
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: qtim
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis-qtim:
        image: redis:7
        container_name: redis-qtim
        restart: always

volumes:
    pgdata:
