version: '3.9'

services:
    backend-qtim:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-qtim
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres-qtim
            - redis-qtim
        environment:
            DB_HOST: postgres-qtim
            REDIS_URL: redis://redis-qtim:6379
        ports:
            - '3000:3000'
        command: >
            sh -c "
              npm run migration:run &&
              npm run prod
            "

    postgres-qtim:
        image: postgres:15
        container_name: postgres-qtim
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: qtim
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis-qtim:
        image: redis:7
        container_name: redis-qtim
        restart: always
        ports:
            - '6379:6379'

volumes:
    pgdata:
